### ISSUE TITLE
Uncaught DivisionByZeroError

### ISSUE THREAD

**Issue by moscowpan** [bit-world/3ndfl#1]
Получаю ошибку в случае если присутствует 0 в удержанном налоге

**Fatal error:** Uncaught DivisionByZeroError: Division by zero in D:\3ndfl-main\src\NDFL3.php:152 Stack trace: #0 D:\3ndfl-main\src\NDFL3.php(206): PDF\NDFL3->gen_income(Array, true) #1 D:\3ndfl-main\index.php(130): PDF\NDFL3->append(Array, true) #2 D:\3ndfl-main\index.php(172): ndfl3_save(Array, false) #3 D:\3ndfl-main\index.php(183): read_file('D:\\3ndfl-main/t...', false, false) #4 {main} thrown in D:\3ndfl-main\src\NDFL3.php on line 152

`$base['in_rub'] = $this->nalog_round($base['in_usd'] * $base['exch_rate'] / $base['exch_base']);`

![Screenshot_416](https://user-images.githubusercontent.com/5447741/152400877-ada5caf4-35f9-461f-80bc-314cf7b6a709.png)

**Comment by bit-world** [comment]
Добрый день, дело точно не в этом, можете прислать полный файл на e-mail?

**Comment by moscowpan** [comment]
Добрый день, подскажите на какой, отправлю.

**Comment by bit-world** [comment]
мойлогин@mail.ru

**Comment by moscowpan** [comment]
отправил

**Comment by bit-world** [comment]
Готово
