### ISSUE TITLE
sample.xls получаю Uncaught DivisionByZeroError: Division by zero

### ISSUE THREAD

**Issue by HappyManWorld** [bit-world/3ndfl#2]
Добрый день.
Спасибо за труд, пока не смог воспользоваться, подскажите что делаю не так.

При использовании приложенного sample.xls получаю 
`Fatal error: Uncaught DivisionByZeroError: Division by zero in C:\Users\user\Desktop\soft\NDFL\3ndfl-main\3ndfl-main\src\NDFL3.php:164 Stack trace: #0 C:\Users\user\Desktop\soft\NDFL\3ndfl-main\3ndfl-main\index.php(40): PDF\NDFL3->gen_income(Array, false) #1 C:\Users\user\Desktop\soft\NDFL\3ndfl-main\3ndfl-main\index.php(177): show_table(Array, true) #2 C:\Users\user\Desktop\soft\NDFL\3ndfl-main\3ndfl-main\index.php(193): read_file('C:\\Users\\user\\D...', true, true) #3 {main} thrown in C:\Users\user\Desktop\soft\NDFL\3ndfl-main\3ndfl-main\src\NDFL3.php on line 1640`

Интерпретатор php-8.3.6-nts-Win32-vs16-x64

**Comment by HappyManWorld** [comment]
Вопрос частично снят, с другой версией работает, но тоже выдает кучу предупреждений! спасибо!
(php-7.4.33-nts-Win32-vc15-x64)

`Warning: Division by zero in C:\Users\user\Desktop\soft\NDFL\3ndfl-main\3ndfl-main\src\NDFL3.php on line 164
Warning: Division by zero in C:\Users\user\Desktop\soft\NDFL\3ndfl-main\3ndfl-main\src\NDFL3.php on line 165
Warning: Division by zero in C:\Users\user\Desktop\soft\NDFL\3ndfl-main\3ndfl-main\index.php on line 50`

**Comment by HappyManRus** [comment]
Причина проста, нужно было в sample.xls поменять дату на 2023 год, вместо 2020.
Видимо курс не подтягивался за 2020 год.
Решено)
Спасибо за софт! часы времени сэкономили!

**Comment by HappyManWorld** [comment]
Причина проста, нужно было в sample.xls поменять дату на 2023 год, вместо 2020.
Видимо курс не подтягивался за 2020 год.
Решено)
Спасибо за софт! часы времени сэкономили!
